---
vlan_id: 3002
vlan_mtu: 9000
up_link: "{{ansible_facts['default_ipv4']['interface']}}"
up_link_mac: "{{ansible_facts['default_ipv4']['macaddress']}}"

ferm_rules:
  default:
    - chain: INPUT
      domains: [ip, ip6]
      rules:
        - {rule: "policy DROP;",  comment: "global policy"}
        - {rule: "saddr 10.10.0.0/16 ACCEPT;", comment: "internal network pods"}
        - {rule: "saddr 10.11.0.0/16 ACCEPT;", comment: "internal network pods"}
        - {rule: "saddr 10.0.6.0/24 ACCEPT;", comment: "internal network pods"}
        - {rule: "saddr 192.168.122.0/24 ACCEPT;", comment: "internal network vm"}
        - {rule: "mod state state INVALID DROP;", comment: "connection tracking: drop"}
        - {rule: "mod state state (ESTABLISHED RELATED) ACCEPT;", comment: "connection tracking"}
        - {rule: "interface lo ACCEPT;", comment: "allow local packet"}
        - {rule: "proto icmp ACCEPT;", comment: "respond to ping"}
        - {rule: "proto udp dport 500 ACCEPT;", comment: "Ipsec"}
        - {rule: "proto tcp dport ssh ACCEPT;", comment: "allow SSH connections"}
        - {rule: "proto tcp dport (http https 444 http-alt 6443 8443) ACCEPT;", comment: "allow HTTP/s and alt"}

        # NodePort won't be used
        # - {rule: "proto tcp dport (30000:33000) ACCEPT;", comment: "allow Kubernetes NodePorts"}
    - chain: OUTPUT
      domains:
        - ip
        - ip6
      rules:
        - rule: "policy ACCEPT;"
          comment: global policy
    - chain: FORWARD
      domains: [ip, ip6]
      rules:
        - rule: "policy ACCEPT;"
          comment: global policy
        - rule: "mod state state INVALID DROP;"
          comment: "connection tracking: drop"
        - rule: "mod state state (ESTABLISHED RELATED) ACCEPT;"
          comment: "connection tracking"
