ferm_rules:
  default:
    - chain: INPUT
      domains: [ip, ip6]
      rules:
        - {rule: "saddr 192.168/8 ACCEPT;", comment: "internal network"}
        - {rule: "policy DROP;",  comment: "global policy"}
        - {rule: "mod state state INVALID DROP;", comment: "connection tracking: drop"}
        - {rule: "mod state state (ESTABLISHED RELATED) ACCEPT;", comment: "connection tracking"}
        - {rule: "interface lo ACCEPT;", comment: "allow local packet"}
        - {rule: "proto icmp ACCEPT;", comment: "respond to ping"}
        - {rule: "proto udp dport 500 ACCEPT;", comment: "Ipsec"}
        - {rule: "proto tcp dport ssh ACCEPT;", comment: "allow SSH connections"}
        - {rule: "proto tcp dport (http https 444 http-alt 6443 8443) ACCEPT;", comment: "allow HTTP/s and alt"}
        - {rule: "proto tcp dport (30000:33000) ACCEPT;", comment: "allow Kubernetes NodePorts"}
    - chain: OUTPUT
      domains:
        - ip
        - ip6
      rules:
        - rule: "policy ACCEPT;"
          comment: global policy
    - chain: FORWARD
      domains: [ip, ip6]
      rules:
        - rule: "policy ACCEPT;"
          comment: global policy
        - rule: "mod state state INVALID DROP;"
          comment: "connection tracking: drop"
        - rule: "mod state state (ESTABLISHED RELATED) ACCEPT;"
          comment: "connection tracking"
